### ISSUE TITLE
PDS4 Viewer: Display Settings Warning

### ISSUE THREAD

**Issue by jennifergward** [Small-Bodies-Node/pds4_tools#101]
PDS4 Viewer gives a warning, "No valid/supported Display Settings found. Displayed image may not be correct," if multiple bands are listed as local_identifier_references in one Display_Settings class rather than in separate classes. Please update the PDS4 Viewer to deal with the recent change to the standards that allows multiple references.

e.g.
<Discipline_Area>
      <disp:Display_Settings>
        <Local_Internal_Reference>
          <local_identifier_reference>INA_at_areoid_image</local_identifier_reference>
          <local_identifier_reference>EMA_at_areoid_image</local_identifier_reference>
          <local_identifier_reference>Phase_angle_image</local_identifier_reference>
          <local_identifier_reference>Latitude_image</local_identifier_reference>
          <local_identifier_reference>Longitude_image</local_identifier_reference>
          <local_identifier_reference>INA_at_surface_from_MOLA_image</local_identifier_reference>
          <local_identifier_reference>EMA_at_surface_from_MOLA_image</local_identifier_reference>
          <local_identifier_reference>Slope_magnitude_from_MOLA_image</local_identifier_reference>
          <local_identifier_reference>MOLA_slope_azimuth_image</local_identifier_reference>
          <local_identifier_reference>Elevation_image</local_identifier_reference>
          <local_identifier_reference>Thermal_inertia_image</local_identifier_reference>
          <local_identifier_reference>Bolometic_albedo_image</local_identifier_reference>
          <local_identifier_reference>Local_solar_time_image</local_identifier_reference>
          <local_identifier_reference>Spare_image</local_identifier_reference>
          <local_reference_type>display_settings_to_array</local_reference_type>
        </Local_Internal_Reference>
        <disp:Display_Direction>
          <disp:horizontal_display_axis>Sample</disp:horizontal_display_axis>
          <disp:horizontal_display_direction>Left to Right</disp:horizontal_display_direction>
          <disp:vertical_display_axis>Line</disp:vertical_display_axis>
          <disp:vertical_display_direction>Top to Bottom</disp:vertical_display_direction>
        </disp:Display_Direction>
      </disp:Display_Settings>

vs. 

<Discipline_Area>
      <disp:Display_Settings>
        <Local_Internal_Reference>
          <local_identifier_reference>INA_at_areoid_image</local_identifier_reference>
          <local_reference_type>display_settings_to_array</local_reference_type>
        </Local_Internal_Reference>
        <disp:Display_Direction>
          <disp:horizontal_display_axis>Sample</disp:horizontal_display_axis>
          <disp:horizontal_display_direction>Left to Right</disp:horizontal_display_direction>
          <disp:vertical_display_axis>Line</disp:vertical_display_axis>
          <disp:vertical_display_direction>Top to Bottom</disp:vertical_display_direction>
        </disp:Display_Direction>
      </disp:Display_Settings>
      <disp:Display_Settings>
        <Local_Internal_Reference>
          <local_identifier_reference>EMA_at_areoid_image</local_identifier_reference>
          <local_reference_type>display_settings_to_array</local_reference_type>
        </Local_Internal_Reference>
        <disp:Display_Direction>
          <disp:horizontal_display_axis>Sample</disp:horizontal_display_axis>
          <disp:horizontal_display_direction>Left to Right</disp:horizontal_display_direction>
          <disp:vertical_display_axis>Line</disp:vertical_display_axis>
          <disp:vertical_display_direction>Top to Bottom</disp:vertical_display_direction>
        </disp:Display_Direction>
      </disp:Display_Settings>
...

**Comment by LevN0** [comment]
Thank you for reporting. This has been on my agenda for a while. I wanted to do a more comprehensive refactoring for discipline dictionaries, but looks like for now I will stick to just addressing this specifically.
