### ISSUE TITLE
Incorrect (?) warning on field_format

### ISSUE THREAD

**Issue by msbentley** [Small-Bodies-Node/pds4_tools#24]
I get the following warning opening a data product:

`Warning: field_format '%+17.10E' does not conform to PDS4 standards for field 'ACC_X' (full location: 'ACC_X') `

which goes away if I replace the upper-case E in the format specifier with a lower case e. However, as far as I can see [from the IM](https://pds.jpl.nasa.gov/datastandards/documents/dd/current/PDS4_PDS_DD_1D00.html#d5e37358) both are allowed, and from the standards doc should be identical:

![image](https://user-images.githubusercontent.com/1671065/79236267-06de7a00-7e6d-11ea-8ea5-035be3b4c59c.png)

Perhaps I'm missing something, but I cannot obviously see what is invalid in the given specifier.

**Comment by LevN0** [comment]
@msbentley,

Believe this issue may have been solved by 09ea30596c6426b60c293a1bcaf3a8cf40fbb58f, can you try the master version?

**Comment by msbentley** [comment]
Yes, the master version fixes that - many thanks!

**Comment by LevN0** [comment]
Glad to hear.
