### ISSUE TITLE
`ArrayStructure.as_masked` fails when input has no masked constants

### ISSUE THREAD

**Issue by LevN0** [Small-Bodies-Node/pds4_tools#30]
User reported issue with visualizing a simple array using PDS4 Viewer. Traced to the following error,

>File "read_arrays.py", line 239, in new_array
>    array_structure.data.set_fill_value(array.fill_value)
>AttributeError: 'PDS_ndarray' object has no attribute 'fill_value'

**Comment by LevN0** [comment]
When the input array does not have any masked values (i.e. Special_Constants is either empty or does not specify constants that should be be masked), but as_masked() is used, a bug kills data read-in.

**Comment by eshaya** [comment]
Lev,

    My two cents.  Not really a bug then.  If something is needed and it
is not there, it should not go ahead anyway.   But, it could be nicer
and provide a fatal error message that a mask is requested but no values
or special constants are defined.

Ed

**Comment by LevN0** [comment]
The design is to always return a masked array when requested. If there are no masked values, the masked array will indicate that but can continue to be used as normal otherwise (a masked array is essentially a wrapper over a normal array with some meta data to indicate which values are masked ... in this case it would indicate none).
