### ISSUE TITLE
pds4_tools should not propagate (lower level) LogRecords when instructed to be quiet

### ISSUE THREAD

**Issue by LandingEllipse** [Small-Bodies-Node/pds4_tools#39]
### Observed behaviour
```
In [1]: import logging

In [2]: logging.basicConfig(level=logging.DEBUG)

In [3]: logger = logging.getLogger("application")

In [4]: logger.info("hello world")
INFO:application:hello world

In [5]: import pds4_tools

In [6]: dp = pds4_tools.read("/tmp/product.xml", quiet=True)
INFO:PDS4ToolsLogger:Processing label: /tmp/product.xml

INFO:PDS4ToolsLogger:Now processing a Table_Delimited structure: TABLE_ANCIL

```
### Desired behaviour
Setting `pds4_tool.read`s keyword argument `quiet` to True prevents `LogRecord`s (below `logging.ERROR`) from propagating up the hierarchy.

### Details
This is possibly getting into opinion territory, but when using PDS4 Tools as a library I would prefer if it respected it's advertised quietness. This is currently not the case because the `quiet` keyword sets the logging level of the package's stdout handler, not that of the "PDS4ToolsLogger" logger itself. I surmise that this is because doing the latter would break the read in log functionality, as the `PDS4SilentHandler` instance would be starved of input.

### Workaround
A minimally intrusive fix would be to add some logic in the already subclassed `PDS4Logger._log` method, to instruct the logger not to propagate records below `_quiet` (i.e. `logging.ERROR`) when `PDS4Logger.is_quiet() == True`. For instance:
```python
def _log(self, level, *args, **kwargs):
    """
    ...
    """
    self.propagate = not (self.is_quiet() and level < _quiet)
    ...
    super(PDS4Logger, self)._log(level, *args, **kwargs)
    ...
```
...where the `level` parameter has been extracted from `args` for readability.

**Comment by LevN0** [comment]
I wonder if PDS4ToolsLogger.propagate should simply be set to False by default?

This avoids potentially disallowing a user from setting a definitive value for it because the value changes on each emitted message as in the proposed fix. And I am not sure whether a default mechanic of True really makes sense here.

**Comment by LandingEllipse** [comment]
Point well taken that we shouldn't hijack/override the public `propagate` attribute - that was ill-considered of me. We can honour any user-set value of `propagate` by throwing an _and_ in there and reverting the attribute after logging:
```python
...
# Emulate PDS4Logger.setLevel(_quiet) while still emitting to "log_handler"
propagate = self.propagate
self.propagate = propagate and not (self.is_quiet() and level < _quiet)

# Log the message
super(PDS4Logger, self)._log(level, *args, **kwargs)

# Revert propagation to previous/default setting
self.propagate = propagate
...
```
This approach will not force propagation of a record if it has been explicitly disabled by a user.

To to expand a bit on the rationale behind this issue's proposal: application developers generally appreciate having control over what level records are emitted/propagated by the loggers of utilised libraries. To use `pds4_tools` as an example, its info-level messages might overlap with those from application-side loggers, or otherwise not be needed. However, it could be desirable to let warnings through, and definitely so with errors and above. Setting `PDS4Logger.propagate` to False by default would prevent any and all of its messages from reaching the application handlers, which is not the desired outcome from this perspective. 

Generally, libraries [don't define their own handlers](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library), so if a library does not provide a way to set its log level via its API, one can always seek out its Logger instance and use `.setLevel()`. But with PDS4 Tools this breaks `StructureList.read_in_log`. The proposed change is intended as a compromise; the application isn't given fine grained control over the level of propagated records, but at least can choose between `_quiet` and `_loud` via the existing `quiet` keyword. No API change, no change to the behaviour of e.g. PDS4 Viewer, just allowing log propagation to act as if the logger's level was set rather than that of the "stdout_handler".

There is still the lingering issue that "stdout_handler" arguably should be disabled in library mode to avoid repeat messages to the console if an application sets `pds4_tools.read(... quiet=False)`. But that change would likely take more than a couple of lines of code to accomplish, and as it's not a burning issue on my end (I'll want to run PDS4 Tools quiet anyway) I'm happy to not poke at that.

**Comment by LevN0** [comment]
Thank you for the thoughts, very valuable to me for understanding what developers using the tool might want. There are a couple possible options to enhance the current logging functionality,

  -> a ``pds4_tools.set_loglevel(level)`` func
  -> adjust behavior of ``pds4_tools.read(quiet=bool)`` and ``pds4_tools.view(quiet=bool)`` arg

The set_loglevel option might be conceptually based on the matplotlib's recent introduction of same. This provides finer-grain control if users want to see or propagate e.g. only warnings or higher.

The question is how the interplay between these should work. At least a couple options come to mind,

  * Option 1:
     - quiet controls only what is output to stdout
     - set_loglevel controls both what is output to stdout when quiet=False, and what gets propagated regardless of quiet=bool

  * Option 2:
     - quiet controls both what is output to stdout and what is propagated (i.e. False means nothing is propagated unless set_loglevel is used)
      - set_loglevel controls both what is output to stdout when quiet=False, and what gets propagated when quiet=True

In either option, propagation is somewhat controlled by set_loglevel, e.g. when the configured level is above the message's level then those messages would not be propagated.

Examining behavior in some model situations:

   * User wants to see only warnings at stdout (no user setup logging)
     - Option 1: quiet=False, set_loglevel('warning') 
     - Option 2: quiet=False, set_loglevel('warning') 

   * User wants to suppress stdout but still receive all messages to their own logger
     - Option 1: quiet=True
     - Option 2: quiet=True, set_loglevel('debug')
   
   * User wants to suppress stdout but still receive only warnings+ to their own logger  
     - Option 1: quiet=True, set_loglevel('warning')
     - Option 2: quiet=True, set_loglevel('warning')

   * User wants to see stdout but suppress all messages in their own logger
     - Option 1: have to set propagate=False to PDS4ToolsLogger
     - Option 2: have to set propagate=False to PDS4ToolsLogger

Option 1 goes against the desired behavior originally suggested above, in that setting quiet=True would still propagate messages unless set_loglevel is used to adjust which messages are propagated. However I wouldn't necessary expect suppress of stdout (via quiet) to affect logging as a user. I keep going back and forth between which option seems better each time I step away and come back to the problem.

I made a working mock-up of these options locally, so I am not asking for an implementation, but rather thoughts for best end-result functionality.

**Comment by LandingEllipse** [comment]
Apologies for the wait; had to drop everything for a week to deal with a delivery.

The `set_loglevel` function would be a sensible addition, and I think that option 1 would be my preference between the two alternatives (with option 2 I am struggling a bit to reason about the interplay between `quiet` and `set_loglevel` even with the model scenarios).

This has me thinking, however, that it might be worth considering an option 3: completely decoupling the stdout handler and log propagation. If `quiet` can optionally take a numeric (or str) log level [1], and it is documented as only affecting the builtin sdout handler ("PDS4 Tools's terminal output"), then that keyword allows finer-grained control over the terminal output, while `set_loglevel` can be allowed only affect log propagation. This would enable for instance:
- User wants to see stdout but but receive only warnings+ to their own logger
  - Option 1: ?
  - Option 2: ?
  - Option 3: quiet=False, set_loglevel('warning')

And it would perhaps make the following scenario a bit simpler for people using `pds4_tools.read` in a notebook setting:
- User wants to see only warnings at stdout (no user setup logging)
  - Option 1: quiet=False, set_loglevel('warning')
  - Option 2: quiet=False, set_loglevel('warning')
  - Option 3: quiet=logging.WARNING  # or quiet="warning" if wanting to take the str route

I suspect that the way one thinks about the role of the stdout handler might affect how one responds to option 3; I tend to see it more as "the terminal output of pds4_tools" than "the builtin *logging* handler of pds4_tools", so I wouldn't be surprised if `set_loglevel` affected only the propagated log records while `quiet` affected the "terminal quietness".


[1] e.g. something like:
```python
log_level = (
    (logging.ERROR if quiet else logging.INFO)
    if isinstance(quiet, bool)
    else quiet  # or use logging.getLevelName(quiet.upper()) with some guards to resolve from string
)
```

**Comment by LevN0** [comment]
Thank you for the additional thoughts.

In the second example you cite, all 3 options should be equally straightforward for a user. quiet=False is default (because we expect more people use the tool for reading data they want to examine than for building tools on top of it), so a single command is necessary in all 3 options to achieve the same effect.

I included the state of quiet in all cases just to make comprehension easier. Same applies for ``logging.WARNING`` vs 'warning' (str), either would work if you are on a version of Python that supports passing strings to ``setLevel`` (at least with options 1 and 2).

>User wants to see all levels above info in stdout but receive only warnings+ to their own logger

The options matrix for all 3 options is,

Note: quiet=False is true by default.

   * User wants to see only warnings at stdout (no user setup logging)
     - Option 1: ~~quiet=False~~, set_loglevel('warning') 
     - Option 2: ~~quiet=False~~, set_loglevel('warning') 
     - Option 3: quiet='warning'

   * User wants to suppress stdout but still receive all messages to their own logger
     - Option 1: quiet=True
     - Option 2: quiet=True, set_loglevel('debug')
     - Option 3: quiet=True
  
   * User wants to suppress stdout but still receive only warnings+ to their own logger  
     - Option 1: quiet=True, set_loglevel('warning')
     - Option 2: quiet=True, set_loglevel('warning')
     - Option 3: quiet=True, set_loglevel('warning')

   * User wants to see stdout but suppress all messages in their own logger
     - Option 1: have to set propagate=False to PDS4ToolsLogger
     - Option 2: have to set propagate=False to PDS4ToolsLogger
     - Option 3: have to set propagate=False to PDS4ToolsLogger [practically set_loglevel('error+') also works]

   * User wants to suppress stdout and all messages to their own logger
     - Option 1: quiet=True, have to set propagate=False to PDS4ToolsLogger [practically set_loglevel('error+') also works]
     - Option 2: quiet=True
     - Option 3: quiet=True, have to set propagate=False to PDS4ToolsLogger [practically set_loglevel('error+') also works]
 
   * User wants to see stdout but receive only warnings+ to their own logger
     - Option 1: have to add ``logging.Filter`` their own logger to filter messages from PDS4ToolsLogger 
     - Option 2: have to add ``logging.Filter`` their own logger to filter messages from PDS4ToolsLogger 
     - Option 3: ~~quiet=False~~, set_loglevel('warning')

When considering option 3 there is a balancing act: achieving behavior in the last model example is easier for the user, at a cost of more complicated implementation and docstring for PDS4 Tools [I did do a mockup implementation of this as well]. How likely is it that anyone would actually want that particular behavior? Let me consult people at SBN.

**Comment by LandingEllipse** [comment]
Thanks for the feedback. I agree that the complexity introduced by option 3 might be difficult to justify; I'll be a happy camper with any of the solutions at this point.

@m-stclair, @cmillion: you use `pds4_tools.read(..., quiet=True)` within `pdr` - do you have any preferences on this?

**Comment by mkelley** [comment]
Hi, at Lev's request, I'll throw in my thoughts here.  I like the idea that quiet controls logging to stdout, and a set_loglevel keyword argument controls all logging messages from pds4_tools, regardless of the handler.  I think this is Option 1.  I think this is easy to describe in documentation, and easy understand for the general user.  Developer documentation can describe how to independently set or add handlers if a user or super-application needs a different behavior.

I don't fully understand the comments about propagation.  But my general expectation is that pds4_tools messages would stop at the top-level handler for the pds4_tools.  Is this a typical approach in Python libraries?  The developer documentation can describe how to change this behavior for applications that use pds4_tools as a library and are interested in consuming the messages (i.e., set propagate to True).

**Comment by LevN0** [comment]
Reviewing this issue, my plan is to implement a 4th option. Will leave this open for a couple days for someone to object before merging. The goal is to decouple the behavior of quiet (which controls output to stdout) and the logging. I.e. we try to make ``quiet`` being implemented with the ``logger`` module an implementation detail. We do however provide fine-grained control for ``quiet``, requested in option 3. By default, we output to stdout but emit nothing to 'log'. 

This is different from a typical Python package -- e.g. matplotlib, requests all emit no messages below warning to stdout by default. In newer versions of Python, I think they emit warning+ messages to stdout by default through the [handler of last resort](https://docs.python.org/3/library/logging.html#logging.lastResort), when no user setup logging is available. astropy emits info+ messages by default, but they use info messages very sparingly. Propagation to lower-level handlers is on by default in all of them. In PDS4 Tools, we choose to emit info+ messages by default to stdout but in a different format than standard logging. Option 4 allows a user to enable regular logging format through ``set_loglevel``, while also being able to disable PDS4 Tools' standard output to stdout  using ``quiet``.

The model behavior for all 4 options is,

Note: quiet=False is true by default.

   * User wants to see only warnings at stdout (no user setup logging)
     - Option 1: ~~quiet=False~~, set_loglevel('warning') 
     - Option 2: ~~quiet=False~~, set_loglevel('warning') 
     - Option 3: quiet='warning'
     - Option 4: quiet='warning'

   * User wants to suppress stdout but still receive all messages to their own logger
     - Option 1: quiet=True
     - Option 2: quiet=True, set_loglevel('debug')
     - Option 3: quiet=True
     - Option 4: quiet=True, set_loglevel('debug')
  
   * User wants to suppress stdout but still receive only warnings+ to their own logger  
     - Option 1: quiet=True, set_loglevel('warning')
     - Option 2: quiet=True, set_loglevel('warning')
     - Option 3: quiet=True, set_loglevel('warning')
     - Option 4: quiet=True, set_loglevel('warning')

   * User wants to see stdout but suppress all messages in their own logger
     - Option 1: have to set propagate=False to PDS4ToolsLogger
     - Option 2: have to set propagate=False to PDS4ToolsLogger
     - Option 3: have to set propagate=False to PDS4ToolsLogger [practically set_loglevel('error+') also works]
     - Option 4: ~~quiet=False~~ 

   * User wants to suppress stdout and all messages to their own logger
     - Option 1: quiet=True, have to set propagate=False to PDS4ToolsLogger [practically set_loglevel('error+') also works]
     - Option 2: quiet=True
     - Option 3: quiet=True, have to set propagate=False to PDS4ToolsLogger [practically set_loglevel('error+') also works]
     - Option 4: quiet=True
 
   * User wants to see stdout but receive only warnings+ to their own logger
     - Option 1: have to add ``logging.Filter`` their own logger to filter messages from PDS4ToolsLogger 
     - Option 2: have to add ``logging.Filter`` their own logger to filter messages from PDS4ToolsLogger 
     - Option 3: ~~quiet=False~~, set_loglevel('warning')
     - Option 3: ~~quiet=False~~, set_loglevel('warning')

**Comment by LandingEllipse** [comment]
Very sensible option you've landed on; PR looks good. Thanks for taking the time to consider, discuss and address this, it is much appreciated!
