### ISSUE TITLE
pds4_tools.view() does not open anything on mac

### ISSUE THREAD

**Issue by michaelaye** [Small-Bodies-Node/pds4_tools#4]
As I'm using macOS 10.14.6 which is not supported (and indeed a quite bad bug it is), I'm trying to use the python route of the viewer.
Trying it in an ipython session, I'm calling `pds4_tools.view()` but nothing happens.
I'm guessing this might need the correct backend setting for the GUI to work. Which backend is required?

**Comment by LevN0** [comment]
Which version of iPython and Python is being used, so I can try to replicate the issue? Backend required is Tkinter/TkAgg, however it should generally set itself - though with iPython this can be more complicated.

**Comment by michaelaye** [comment]
i guess some of my settings block it, an `ipython --quick` session that leaves out start-up files removes the blockage of the GUI.
However, things still do not work, will make a new issue later.

**Comment by LevN0** [comment]
The Viewer will now try to detect that IPython is initialized with an incorrect backend, warn, and try to provide a solution. 

OS X 10.14.6 bug remains unresolved, however I think Apple fixed it in 10.15.1.
