### ISSUE TITLE
Version of Six causing warnings in python 3.11

### ISSUE THREAD

**Issue by dahlend** [Small-Bodies-Node/pds4_tools#70]
I've been having a few issues using python 3.10/3.11 with this package due to the older version of the `Six` package which appears to be copied into the `Extern` folder. 

See the discussion here: https://github.com/benjaminp/six/issues/341

Specifically the newer versions of Six have this: https://github.com/benjaminp/six/blob/master/six.py#L194 to be defined.

Potential solutions:
- Update this `six.py` file
- Update the package installation method so that pip will automatically grab the latest package versions instead of having an `extern` folder.
- Remove support for python 2?

**Comment by LevN0** [comment]
Thank you for reporting. Looks like there are some tests that are breaking, though probably unrelated. Let me look into it.
