### ISSUE TITLE
to_dict method | Reference_List dictionary - sub-groups collapse

### ISSUE THREAD

**Issue by Fenreg** [Small-Bodies-Node/pds4_tools#91]
Dear @LevN0,

I found out that the to_dict method has apparently an issue when dealing with a Reference_List, and apparently collapses the duplicate sub-groups into a single one.
Consider a Reference_List containing multiple Internal_Reference labels set as below:
![image](https://github.com/Small-Bodies-Node/pds4_tools/assets/31766605/d24d77ee-f0fd-4714-8bcd-f16305db2ce4)
Which when read as follows:
![image](https://github.com/Small-Bodies-Node/pds4_tools/assets/31766605/f1a63c50-5db9-4c41-9470-25b8a08dbff6)
Provides the following results:
![image](https://github.com/Small-Bodies-Node/pds4_tools/assets/31766605/3a90edb1-87be-45d9-8cf8-f15ba4050ed4)

My understanding is that this feature happens despite the  Reference_List being structured as expected according the Information model specs (https://pds.nasa.gov/datastandards/documents/im/v1/index_1K00.html#reference_type).

Could you throw maybe some light on this ?
Looking forward to your reply,
All the best

**Comment by LevN0** [comment]
I may be misunderstanding, but I think the result you are seeing is what I would expect.

```xml
<Reference_List>
	<Internal_Reference>
		<lid_reference>1</lid_reference>
		<reference_type>1b</reference_type>
		<comment>1c</comment>
	</Internal_Reference>
	<Internal_Reference>
		<lid_reference>2a</lid_reference>
		<reference_type>2b</reference_type>
		<comment>2c</comment>
	</Internal_Reference>
</Reference_List>
```

Should translate to

```python

dict_label = {
    'Reference_List': {
        'Internal_Reference': [
            {
                  'lid_reference': '1a',
                  'reference_type': '1b',
                  'comment': '1c'
            },
            {
                  'lid_reference': '2a',
                  'reference_type': '2b',
                  'comment': '2c'
            }
        ]
    }
}
```

Is this not what you see, or not what you expect? If the latter, what did you expect?

**Comment by LevN0** [comment]
@Fenreg 

Following up on this one. If I don't hear back from you, I'll go ahead and assume this as resolved.
