### ISSUE TITLE
PDS_marray.view() failing on numpy >= 2.0.0

### ISSUE THREAD

**Issue by m-stclair** [Small-Bodies-Node/pds4_tools#94]
Numpy 2.0.0 removes `np.issubclass_()`. `pds4_tools.reader.data.PDS_marray.view()` calls this function, so fails with an `AttributeError`. All numpy objects are now supposed to behave properly with the `issubclass()` builtin, so that should be a drop-in replacement.

**Comment by LevN0** [comment]
Thank you for reporting. Will take a look at this, and what else NumPy 2.0 breaks.
